// ---------------------------------------------------------------------------
// Nationality-aware name pools
// ---------------------------------------------------------------------------

pub(super) struct NationalityNames {
    pub nationality: &'static str,
    pub first_names: &'static [&'static str],
    pub last_names: &'static [&'static str],
}

pub(super) const NATIONALITY_POOLS: &[NationalityNames] = &[
    NationalityNames {
        nationality: "ENG",
        first_names: &[
            "James", "Harry", "Jack", "Oliver", "George", "Charlie", "Thomas", "William", "Daniel",
            "Ben", "Luke", "Ryan", "Sam", "Callum", "Nathan", "Adam", "Liam", "Marcus", "Ethan",
            "Mason",
        ],
        last_names: &[
            "Smith", "Johnson", "Brown", "Jones", "Taylor", "Wilson", "Walker", "Robinson",
            "Clark", "Wright", "Hall", "Green", "Baker", "Hill", "Allen", "Young", "King",
            "Cooper", "Parker", "Turner",
        ],
    },
    NationalityNames {
        nationality: "SCO",
        first_names: &[
            "Jack", "Lewis", "Fraser", "Ross", "Callum", "Scott", "Ryan", "Ewan", "Craig",
            "Stuart", "Cameron", "Kieran", "Jamie", "Gregor", "Finlay", "Liam", "Arran", "Declan",
            "Blair", "Dylan",
        ],
        last_names: &[
            "McDonald",
            "Stewart",
            "Robertson",
            "Campbell",
            "Anderson",
            "Scott",
            "Reid",
            "Murray",
            "Ross",
            "Paterson",
            "Ferguson",
            "MacLeod",
            "Johnston",
            "Morrison",
            "Walker",
            "Bell",
            "Fraser",
            "Clark",
            "Sutherland",
            "Graham",
        ],
    },
    NationalityNames {
        nationality: "WAL",
        first_names: &[
            "Rhys", "Dylan", "Owain", "Gethin", "Harri", "Cai", "Ioan", "Evan", "Morgan", "Ellis",
            "Tomos", "Aneurin", "Lloyd", "Osian", "Jac", "Ieuan", "Bryn", "Steffan", "Carwyn",
            "Gruffydd",
        ],
        last_names: &[
            "Jones",
            "Williams",
            "Davies",
            "Evans",
            "Thomas",
            "Roberts",
            "Lewis",
            "Morgan",
            "Griffiths",
            "Hughes",
            "Price",
            "Rees",
            "Jenkins",
            "Owen",
            "Lloyd",
            "Edwards",
            "Pritchard",
            "Powell",
            "Vaughan",
            "Parry",
        ],
    },
    NationalityNames {
        nationality: "NIR",
        first_names: &[
            "Conor", "Ryan", "Niall", "Ciaran", "Eoin", "Sean", "Darragh", "Ronan", "Cathal",
            "Paddy", "Shane", "Rory", "Callum", "Odhran", "Aidan", "Ethan", "Johnny", "Reece",
            "Aaron", "Daniel",
        ],
        last_names: &[
            "McCann",
            "O'Neill",
            "Murphy",
            "Doherty",
            "McLaughlin",
            "Quinn",
            "McKenna",
            "Gallagher",
            "Devlin",
            "Maguire",
            "Boyle",
            "McAllister",
            "McBride",
            "McCormick",
            "Campbell",
            "McGrath",
            "Mullan",
            "Morrow",
            "Moore",
            "Lavery",
        ],
    },
    NationalityNames {
        nationality: "IE",
        first_names: &[
            "Sean", "Conor", "Cian", "Darragh", "Oisin", "Padraig", "Tadhg", "Eoin", "Ronan",
            "Fionn", "Cillian", "Brian", "Aidan", "Shane", "Diarmuid", "Niall", "Ruairi", "Cathal",
            "Liam", "Jack",
        ],
        last_names: &[
            "Murphy",
            "Kelly",
            "Byrne",
            "Ryan",
            "O'Brien",
            "Walsh",
            "Doyle",
            "McCarthy",
            "Gallagher",
            "Kennedy",
            "Lynch",
            "Murray",
            "Quinn",
            "Moore",
            "Dunne",
            "Carroll",
            "Connolly",
            "Sullivan",
            "Brennan",
            "Power",
        ],
    },
    NationalityNames {
        nationality: "GB",
        first_names: &[
            "James", "Harry", "Jack", "Oliver", "George", "Charlie", "Thomas", "William", "Daniel",
            "Ben", "Luke", "Ryan", "Joe", "Sam", "Callum", "Nathan", "Ross", "Adam", "Liam",
            "Marcus",
        ],
        last_names: &[
            "Smith", "Johnson", "Williams", "Brown", "Jones", "Taylor", "Wilson", "Davies",
            "Evans", "Walker", "Robinson", "Clark", "Wright", "Hall", "Green", "Baker", "Hill",
            "Allen", "Young", "King",
        ],
    },
    NationalityNames {
        nationality: "ES",
        first_names: &[
            "Sergio",
            "Pablo",
            "Alejandro",
            "Carlos",
            "Javier",
            "Miguel",
            "Raul",
            "David",
            "Andres",
            "Alvaro",
            "Hugo",
            "Iker",
            "Marcos",
            "Luis",
            "Pedro",
            "Adrian",
            "Diego",
            "Fernando",
            "Gonzalo",
            "Antonio",
        ],
        last_names: &[
            "Garcia",
            "Rodriguez",
            "Martinez",
            "Lopez",
            "Sanchez",
            "Fernandez",
            "Gonzalez",
            "Hernandez",
            "Moreno",
            "Ruiz",
            "Diaz",
            "Alvarez",
            "Romero",
            "Torres",
            "Navarro",
            "Gil",
            "Vega",
            "Ramos",
            "Ortiz",
            "Castro",
        ],
    },
    NationalityNames {
        nationality: "DE",
        first_names: &[
            "Lukas",
            "Niklas",
            "Leon",
            "Felix",
            "Maximilian",
            "Jonas",
            "Florian",
            "Julian",
            "Tim",
            "Jan",
            "Kevin",
            "Marco",
            "Kai",
            "Stefan",
            "Patrick",
            "Dennis",
            "Tobias",
            "Marcel",
            "Timo",
            "Lars",
        ],
        last_names: &[
            "Müller",
            "Schmidt",
            "Schneider",
            "Fischer",
            "Weber",
            "Meyer",
            "Wagner",
            "Becker",
            "Schulz",
            "Hoffmann",
            "Koch",
            "Richter",
            "Wolf",
            "Schäfer",
            "Neumann",
            "Schwarz",
            "Zimmermann",
            "Braun",
            "Hartmann",
            "Krüger",
        ],
    },
    NationalityNames {
        nationality: "FR",
        first_names: &[
            "Antoine",
            "Hugo",
            "Lucas",
            "Mathieu",
            "Julien",
            "Maxime",
            "Pierre",
            "Thomas",
            "Raphael",
            "Adrien",
            "Kevin",
            "Alexandre",
            "Nicolas",
            "Loic",
            "Clement",
            "Florian",
            "Theo",
            "Damien",
            "Yann",
            "Baptiste",
        ],
        last_names: &[
            "Martin", "Bernard", "Dubois", "Thomas", "Robert", "Petit", "Moreau", "Laurent",
            "Simon", "Michel", "Lefevre", "Leroy", "Roux", "David", "Bertrand", "Morel",
            "Fournier", "Girard", "Bonnet", "Dupont",
        ],
    },
    NationalityNames {
        nationality: "IT",
        first_names: &[
            "Marco",
            "Luca",
            "Andrea",
            "Matteo",
            "Alessandro",
            "Lorenzo",
            "Davide",
            "Simone",
            "Riccardo",
            "Federico",
            "Gianluca",
            "Stefano",
            "Fabio",
            "Roberto",
            "Nicola",
            "Salvatore",
            "Daniele",
            "Paolo",
            "Vincenzo",
            "Emanuele",
        ],
        last_names: &[
            "Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci",
            "Marino", "Greco", "Bruno", "Gallo", "Conti", "De Luca", "Costa", "Mancini",
            "Barbieri", "Fontana", "Santoro", "Rinaldi",
        ],
    },
    NationalityNames {
        nationality: "NL",
        first_names: &[
            "Daan", "Sem", "Lars", "Tim", "Thomas", "Jesse", "Jordi", "Luuk", "Rick", "Bas",
            "Stijn", "Nick", "Davy", "Wesley", "Kevin", "Robin", "Sander", "Ruud", "Dennis",
            "Patrick",
        ],
        last_names: &[
            "De Jong",
            "Van Dijk",
            "Jansen",
            "De Vries",
            "Van den Berg",
            "Bakker",
            "Visser",
            "Smit",
            "Meijer",
            "De Boer",
            "Mulder",
            "Dekker",
            "Peters",
            "Hendriks",
            "Van Leeuwen",
            "De Graaf",
            "Kok",
            "Brouwer",
            "Vermeer",
            "Van Dam",
        ],
    },
    NationalityNames {
        nationality: "PT",
        first_names: &[
            "Rui", "Joao", "Bruno", "Diogo", "Pedro", "Tiago", "Nuno", "Miguel", "Andre",
            "Goncalo", "Rafael", "Luis", "Ricardo", "Hugo", "Fabio", "Bernardo", "Daniel", "Vitor",
            "Nelson", "Sergio",
        ],
        last_names: &[
            "Silva",
            "Santos",
            "Ferreira",
            "Costa",
            "Pereira",
            "Oliveira",
            "Rodrigues",
            "Martins",
            "Sousa",
            "Fernandes",
            "Goncalves",
            "Lopes",
            "Almeida",
            "Carvalho",
            "Ribeiro",
            "Pinto",
            "Teixeira",
            "Mendes",
            "Neves",
            "Vieira",
        ],
    },
    NationalityNames {
        nationality: "BR",
        first_names: &[
            "Lucas",
            "Gabriel",
            "Rafael",
            "Matheus",
            "Guilherme",
            "Felipe",
            "Thiago",
            "Vinicius",
            "Pedro",
            "Gustavo",
            "Bruno",
            "Leonardo",
            "Anderson",
            "Douglas",
            "Eduardo",
            "Henrique",
            "Marcelo",
            "Diego",
            "Igor",
            "Leandro",
        ],
        last_names: &[
            "Silva",
            "Santos",
            "Oliveira",
            "Souza",
            "Pereira",
            "Costa",
            "Ferreira",
            "Rodrigues",
            "Almeida",
            "Nascimento",
            "Lima",
            "Araujo",
            "Ribeiro",
            "Carvalho",
            "Gomes",
            "Martins",
            "Rocha",
            "Mendes",
            "Barbosa",
            "Moreira",
        ],
    },
    NationalityNames {
        nationality: "AR",
        first_names: &[
            "Lionel", "Gonzalo", "Angel", "Sergio", "Nicolas", "Pablo", "Mauro", "Lucas",
            "Ezequiel", "Javier", "Marcos", "Leandro", "Federico", "Ignacio", "Rodrigo", "Matias",
            "Franco", "Agustin", "Julian", "Cristian",
        ],
        last_names: &[
            "Gonzalez",
            "Rodriguez",
            "Martinez",
            "Lopez",
            "Fernandez",
            "Garcia",
            "Romero",
            "Diaz",
            "Torres",
            "Sanchez",
            "Alvarez",
            "Acosta",
            "Gutierrez",
            "Castro",
            "Pereyra",
            "Aguero",
            "Ruiz",
            "Herrera",
            "Medina",
            "Flores",
        ],
    },
    NationalityNames {
        nationality: "BE",
        first_names: &[
            "Kevin", "Eden", "Romelu", "Dries", "Yannick", "Thomas", "Axel", "Thorgan", "Michy",
            "Nacer", "Radja", "Jan", "Toby", "Simon", "Leander", "Jason", "Timothy", "Hans",
            "Dennis", "Laurent",
        ],
        last_names: &[
            "Janssens", "Peeters", "Maes", "Jacobs", "Mertens", "Willems", "Claes", "Goossens",
            "Wouters", "De Smet", "Hermans", "Peters", "Stevens", "Leclercq", "Lambert", "Dupont",
            "Dumont", "Simon", "Laurent", "Renard",
        ],
    },
    NationalityNames {
        nationality: "HR",
        first_names: &[
            "Luka", "Ivan", "Mateo", "Mario", "Dejan", "Ante", "Josip", "Marko", "Nikola",
            "Marcelo", "Andrej", "Darijo", "Sime", "Borna", "Domagoj", "Vedran", "Duje", "Filip",
            "Tin", "Bruno",
        ],
        last_names: &[
            "Kovacic",
            "Horvat",
            "Babic",
            "Maric",
            "Juric",
            "Novak",
            "Perisic",
            "Tomic",
            "Vucinic",
            "Brozovic",
            "Kramaric",
            "Vidovic",
            "Lovren",
            "Srna",
            "Rakitic",
            "Modric",
            "Pasalic",
            "Rebic",
            "Livakovic",
            "Gvardiol",
        ],
    },
    NationalityNames {
        nationality: "SE",
        first_names: &[
            "Emil",
            "Oscar",
            "Viktor",
            "Erik",
            "Alexander",
            "Marcus",
            "Sebastian",
            "Filip",
            "Albin",
            "Robin",
            "Pontus",
            "Mattias",
            "Andreas",
            "Gustav",
            "Kristoffer",
            "Joel",
            "Ludwig",
            "Simon",
            "Martin",
            "Henrik",
        ],
        last_names: &[
            "Andersson",
            "Johansson",
            "Karlsson",
            "Nilsson",
            "Eriksson",
            "Larsson",
            "Olsson",
            "Persson",
            "Svensson",
            "Gustafsson",
            "Pettersson",
            "Jonsson",
            "Jansson",
            "Hansson",
            "Bengtsson",
            "Lindberg",
            "Lundqvist",
            "Forsberg",
            "Lindqvist",
            "Berg",
        ],
    },
];

// ---------------------------------------------------------------------------
// Team data — realistic European default world
// ---------------------------------------------------------------------------

pub(super) struct TeamTemplate {
    pub name: &'static str,
    pub city: &'static str,
    pub country: &'static str,
    pub domestic_tier: u8,
    pub colors: (&'static str, &'static str),
    pub play_style: &'static str,
}

macro_rules! team {
    ($name:literal, $city:literal, $country:literal, $tier:literal, $primary:literal, $secondary:literal, $style:literal) => {
        TeamTemplate {
            name: $name,
            city: $city,
            country: $country,
            domestic_tier: $tier,
            colors: ($primary, $secondary),
            play_style: $style,
        }
    };
}

pub(super) const TEAM_TEMPLATES: &[TeamTemplate] = &[
    team!("Arsenal", "London", "England", 1, "#dc2626", "#ffffff", "Possession"),
    team!("Aston Villa", "Birmingham", "England", 1, "#7c2d12", "#60a5fa", "Counter"),
    team!("Bournemouth", "Bournemouth", "England", 1, "#ef4444", "#111827", "HighPress"),
    team!("Brentford", "London", "England", 1, "#ef4444", "#ffffff", "Balanced"),
    team!("Brighton & Hove Albion", "Brighton", "England", 1, "#2563eb", "#ffffff", "Possession"),
    team!("Chelsea", "London", "England", 1, "#1d4ed8", "#ffffff", "Attacking"),
    team!("Crystal Palace", "London", "England", 1, "#1d4ed8", "#dc2626", "Counter"),
    team!("Everton", "Liverpool", "England", 1, "#1d4ed8", "#ffffff", "Balanced"),
    team!("Fulham", "London", "England", 1, "#ffffff", "#111827", "Possession"),
    team!("Ipswich Town", "Ipswich", "England", 1, "#1d4ed8", "#ffffff", "Balanced"),
    team!("Leicester City", "Leicester", "England", 1, "#2563eb", "#ffffff", "Counter"),
    team!("Liverpool", "Liverpool", "England", 1, "#b91c1c", "#fbbf24", "HighPress"),
    team!("Manchester City", "Manchester", "England", 1, "#60a5fa", "#1e3a5f", "Possession"),
    team!("Manchester United", "Manchester", "England", 1, "#dc2626", "#fbbf24", "Attacking"),
    team!("Newcastle United", "Newcastle upon Tyne", "England", 1, "#111827", "#ffffff", "HighPress"),
    team!("Nottingham Forest", "Nottingham", "England", 1, "#dc2626", "#ffffff", "Counter"),
    team!("Southampton", "Southampton", "England", 1, "#ef4444", "#ffffff", "Possession"),
    team!("Tottenham Hotspur", "London", "England", 1, "#ffffff", "#1e3a5f", "Attacking"),
    team!("West Ham United", "London", "England", 1, "#7f1d1d", "#93c5fd", "Balanced"),
    team!("Wolverhampton Wanderers", "Wolverhampton", "England", 1, "#f59e0b", "#111827", "Counter"),
    team!("Blackburn Rovers", "Blackburn", "England", 2, "#ffffff", "#2563eb", "Balanced"),
    team!("Bristol City", "Bristol", "England", 2, "#dc2626", "#ffffff", "HighPress"),
    team!("Burnley", "Burnley", "England", 2, "#7f1d1d", "#93c5fd", "Balanced"),
    team!("Cardiff City", "Cardiff", "England", 2, "#1d4ed8", "#ffffff", "Counter"),
    team!("Coventry City", "Coventry", "England", 2, "#60a5fa", "#ffffff", "Possession"),
    team!("Derby County", "Derby", "England", 2, "#ffffff", "#111827", "Balanced"),
    team!("Hull City", "Hull", "England", 2, "#f97316", "#111827", "Counter"),
    team!("Leeds United", "Leeds", "England", 2, "#ffffff", "#1d4ed8", "HighPress"),
    team!("Luton Town", "Luton", "England", 2, "#f97316", "#1e3a8a", "Counter"),
    team!("Middlesbrough", "Middlesbrough", "England", 2, "#dc2626", "#ffffff", "Balanced"),
    team!("Millwall", "London", "England", 2, "#1e3a8a", "#ffffff", "Defensive"),
    team!("Norwich City", "Norwich", "England", 2, "#facc15", "#16a34a", "Possession"),
    team!("Oxford United", "Oxford", "England", 2, "#facc15", "#1d4ed8", "Balanced"),
    team!("Plymouth Argyle", "Plymouth", "England", 2, "#166534", "#ffffff", "Counter"),
    team!("Portsmouth", "Portsmouth", "England", 2, "#1d4ed8", "#ffffff", "HighPress"),
    team!("Preston North End", "Preston", "England", 2, "#ffffff", "#1e3a8a", "Balanced"),
    team!("Queens Park Rangers", "London", "England", 2, "#2563eb", "#ffffff", "Possession"),
    team!("Sheffield United", "Sheffield", "England", 2, "#dc2626", "#ffffff", "HighPress"),
    team!("Stoke City", "Stoke-on-Trent", "England", 2, "#dc2626", "#ffffff", "Defensive"),
    team!("Sunderland", "Sunderland", "England", 2, "#dc2626", "#ffffff", "Attacking"),

    team!("Paris Saint-Germain", "Paris", "France", 1, "#1e3a8a", "#dc2626", "Attacking"),
    team!("Marseille", "Marseille", "France", 1, "#38bdf8", "#ffffff", "HighPress"),
    team!("Monaco", "Monaco", "France", 1, "#ef4444", "#ffffff", "Counter"),
    team!("Lyon", "Lyon", "France", 1, "#1d4ed8", "#ffffff", "Possession"),
    team!("Lille", "Lille", "France", 1, "#dc2626", "#1e3a8a", "Balanced"),
    team!("Nice", "Nice", "France", 1, "#dc2626", "#111827", "Counter"),
    team!("Rennes", "Rennes", "France", 1, "#dc2626", "#111827", "HighPress"),
    team!("Lens", "Lens", "France", 1, "#dc2626", "#facc15", "HighPress"),
    team!("Strasbourg", "Strasbourg", "France", 1, "#2563eb", "#ffffff", "Balanced"),
    team!("Nantes", "Nantes", "France", 1, "#facc15", "#16a34a", "Possession"),
    team!("Montpellier", "Montpellier", "France", 1, "#f97316", "#1e3a8a", "Counter"),
    team!("Toulouse", "Toulouse", "France", 1, "#7c3aed", "#ffffff", "Possession"),
    team!("Brest", "Brest", "France", 1, "#dc2626", "#ffffff", "Balanced"),
    team!("Reims", "Reims", "France", 1, "#dc2626", "#ffffff", "Balanced"),
    team!("Le Havre", "Le Havre", "France", 1, "#60a5fa", "#1e3a8a", "Defensive"),
    team!("Saint-Étienne", "Saint-Étienne", "France", 1, "#16a34a", "#ffffff", "HighPress"),
    team!("Auxerre", "Auxerre", "France", 1, "#ffffff", "#2563eb", "Counter"),
    team!("Angers", "Angers", "France", 1, "#111827", "#ffffff", "Defensive"),
    team!("Ajaccio", "Ajaccio", "France", 2, "#dc2626", "#ffffff", "Defensive"),
    team!("Amiens", "Amiens", "France", 2, "#111827", "#ffffff", "Balanced"),
    team!("Annecy", "Annecy", "France", 2, "#dc2626", "#ffffff", "Counter"),
    team!("Bastia", "Bastia", "France", 2, "#2563eb", "#ffffff", "HighPress"),
    team!("Caen", "Caen", "France", 2, "#1d4ed8", "#dc2626", "Possession"),
    team!("Clermont", "Clermont-Ferrand", "France", 2, "#7f1d1d", "#2563eb", "Balanced"),
    team!("Dunkerque", "Dunkerque", "France", 2, "#ffffff", "#1d4ed8", "Counter"),
    team!("Grenoble", "Grenoble", "France", 2, "#1d4ed8", "#ffffff", "Defensive"),
    team!("Guingamp", "Guingamp", "France", 2, "#dc2626", "#111827", "HighPress"),
    team!("Laval", "Laval", "France", 2, "#f97316", "#111827", "Counter"),
    team!("Lorient", "Lorient", "France", 2, "#f97316", "#111827", "Possession"),
    team!("Martigues", "Martigues", "France", 2, "#dc2626", "#facc15", "Balanced"),
    team!("Metz", "Metz", "France", 2, "#7f1d1d", "#ffffff", "Balanced"),
    team!("Paris FC", "Paris", "France", 2, "#1e3a8a", "#ffffff", "Possession"),
    team!("Pau", "Pau", "France", 2, "#facc15", "#1d4ed8", "Counter"),
    team!("Red Star", "Saint-Ouen", "France", 2, "#16a34a", "#ffffff", "HighPress"),
    team!("Rodez", "Rodez", "France", 2, "#dc2626", "#facc15", "Balanced"),
    team!("Troyes", "Troyes", "France", 2, "#2563eb", "#ffffff", "Possession"),

    team!("Bayern Munich", "Munich", "Germany", 1, "#dc2626", "#ffffff", "HighPress"),
    team!("Borussia Dortmund", "Dortmund", "Germany", 1, "#facc15", "#111827", "Attacking"),
    team!("Bayer Leverkusen", "Leverkusen", "Germany", 1, "#dc2626", "#111827", "Possession"),
    team!("RB Leipzig", "Leipzig", "Germany", 1, "#ffffff", "#dc2626", "HighPress"),
    team!("Eintracht Frankfurt", "Frankfurt", "Germany", 1, "#dc2626", "#111827", "Counter"),
    team!("Stuttgart", "Stuttgart", "Germany", 1, "#ffffff", "#dc2626", "Possession"),
    team!("Freiburg", "Freiburg", "Germany", 1, "#dc2626", "#111827", "Balanced"),
    team!("Hoffenheim", "Sinsheim", "Germany", 1, "#2563eb", "#ffffff", "Attacking"),
    team!("Werder Bremen", "Bremen", "Germany", 1, "#16a34a", "#ffffff", "Possession"),
    team!("Wolfsburg", "Wolfsburg", "Germany", 1, "#16a34a", "#ffffff", "Counter"),
    team!("Borussia Mönchengladbach", "Mönchengladbach", "Germany", 1, "#ffffff", "#16a34a", "Balanced"),
    team!("Mainz 05", "Mainz", "Germany", 1, "#dc2626", "#ffffff", "HighPress"),
    team!("Union Berlin", "Berlin", "Germany", 1, "#dc2626", "#facc15", "Defensive"),
    team!("Augsburg", "Augsburg", "Germany", 1, "#dc2626", "#16a34a", "Counter"),
    team!("Bochum", "Bochum", "Germany", 1, "#1d4ed8", "#ffffff", "Defensive"),
    team!("Heidenheim", "Heidenheim", "Germany", 1, "#dc2626", "#1d4ed8", "Balanced"),
    team!("St. Pauli", "Hamburg", "Germany", 1, "#7c2d12", "#ffffff", "HighPress"),
    team!("Holstein Kiel", "Kiel", "Germany", 1, "#1d4ed8", "#ffffff", "Possession"),
    team!("Schalke 04", "Gelsenkirchen", "Germany", 2, "#1d4ed8", "#ffffff", "HighPress"),
    team!("Hamburger SV", "Hamburg", "Germany", 2, "#1d4ed8", "#ffffff", "Attacking"),
    team!("Hertha BSC", "Berlin", "Germany", 2, "#2563eb", "#ffffff", "Possession"),
    team!("Hannover 96", "Hannover", "Germany", 2, "#16a34a", "#111827", "Counter"),
    team!("Kaiserslautern", "Kaiserslautern", "Germany", 2, "#dc2626", "#ffffff", "HighPress"),
    team!("Karlsruher SC", "Karlsruhe", "Germany", 2, "#2563eb", "#ffffff", "Balanced"),
    team!("Fortuna Düsseldorf", "Düsseldorf", "Germany", 2, "#dc2626", "#ffffff", "Possession"),
    team!("Nürnberg", "Nuremberg", "Germany", 2, "#7f1d1d", "#ffffff", "Balanced"),
    team!("Paderborn", "Paderborn", "Germany", 2, "#1d4ed8", "#111827", "Counter"),
    team!("Greuther Fürth", "Fürth", "Germany", 2, "#16a34a", "#ffffff", "Balanced"),
    team!("Magdeburg", "Magdeburg", "Germany", 2, "#2563eb", "#ffffff", "Attacking"),
    team!("Elversberg", "Spiesen-Elversberg", "Germany", 2, "#111827", "#ffffff", "Counter"),
    team!("Preußen Münster", "Münster", "Germany", 2, "#16a34a", "#111827", "Defensive"),
    team!("Jahn Regensburg", "Regensburg", "Germany", 2, "#dc2626", "#ffffff", "Balanced"),
    team!("Ulm", "Ulm", "Germany", 2, "#111827", "#ffffff", "Counter"),
    team!("Darmstadt 98", "Darmstadt", "Germany", 2, "#1d4ed8", "#ffffff", "Possession"),
    team!("Eintracht Braunschweig", "Braunschweig", "Germany", 2, "#facc15", "#2563eb", "Balanced"),
    team!("Köln", "Cologne", "Germany", 2, "#dc2626", "#ffffff", "HighPress"),

    team!("Inter Milan", "Milan", "Italy", 1, "#1d4ed8", "#111827", "Counter"),
    team!("AC Milan", "Milan", "Italy", 1, "#dc2626", "#111827", "Attacking"),
    team!("Juventus", "Turin", "Italy", 1, "#111827", "#ffffff", "Possession"),
    team!("Napoli", "Naples", "Italy", 1, "#0ea5e9", "#ffffff", "Attacking"),
    team!("Roma", "Rome", "Italy", 1, "#7f1d1d", "#f59e0b", "Counter"),
    team!("Lazio", "Rome", "Italy", 1, "#60a5fa", "#ffffff", "Balanced"),
    team!("Atalanta", "Bergamo", "Italy", 1, "#1d4ed8", "#111827", "HighPress"),
    team!("Fiorentina", "Florence", "Italy", 1, "#7c3aed", "#ffffff", "Possession"),
    team!("Bologna", "Bologna", "Italy", 1, "#1d4ed8", "#dc2626", "Balanced"),
    team!("Torino", "Turin", "Italy", 1, "#7f1d1d", "#ffffff", "Defensive"),
    team!("Genoa", "Genoa", "Italy", 1, "#1d4ed8", "#dc2626", "Counter"),
    team!("Udinese", "Udine", "Italy", 1, "#111827", "#ffffff", "Balanced"),
    team!("Monza", "Monza", "Italy", 1, "#dc2626", "#ffffff", "Possession"),
    team!("Cagliari", "Cagliari", "Italy", 1, "#1e3a8a", "#7f1d1d", "Counter"),
    team!("Empoli", "Empoli", "Italy", 1, "#2563eb", "#ffffff", "Defensive"),
    team!("Lecce", "Lecce", "Italy", 1, "#dc2626", "#facc15", "HighPress"),
    team!("Parma", "Parma", "Italy", 1, "#facc15", "#1d4ed8", "Possession"),
    team!("Como", "Como", "Italy", 1, "#2563eb", "#ffffff", "Balanced"),
    team!("Venezia", "Venice", "Italy", 1, "#f97316", "#16a34a", "Counter"),
    team!("Hellas Verona", "Verona", "Italy", 1, "#1e3a8a", "#facc15", "Defensive"),
    team!("Bari", "Bari", "Italy", 2, "#dc2626", "#ffffff", "Attacking"),
    team!("Brescia", "Brescia", "Italy", 2, "#2563eb", "#ffffff", "Balanced"),
    team!("Carrarese", "Carrara", "Italy", 2, "#60a5fa", "#ffffff", "Counter"),
    team!("Catanzaro", "Catanzaro", "Italy", 2, "#dc2626", "#facc15", "HighPress"),
    team!("Cesena", "Cesena", "Italy", 2, "#111827", "#ffffff", "Balanced"),
    team!("Cittadella", "Cittadella", "Italy", 2, "#7f1d1d", "#ffffff", "Defensive"),
    team!("Cosenza", "Cosenza", "Italy", 2, "#1d4ed8", "#dc2626", "Counter"),
    team!("Cremonese", "Cremona", "Italy", 2, "#dc2626", "#9ca3af", "Possession"),
    team!("Frosinone", "Frosinone", "Italy", 2, "#facc15", "#1d4ed8", "Attacking"),
    team!("Juve Stabia", "Castellammare di Stabia", "Italy", 2, "#facc15", "#1d4ed8", "Counter"),
    team!("Mantova", "Mantua", "Italy", 2, "#dc2626", "#ffffff", "Balanced"),
    team!("Modena", "Modena", "Italy", 2, "#facc15", "#1d4ed8", "Possession"),
    team!("Palermo", "Palermo", "Italy", 2, "#f472b6", "#111827", "Attacking"),
    team!("Pisa", "Pisa", "Italy", 2, "#1d4ed8", "#111827", "HighPress"),
    team!("Reggiana", "Reggio Emilia", "Italy", 2, "#dc2626", "#ffffff", "Balanced"),
    team!("Salernitana", "Salerno", "Italy", 2, "#7f1d1d", "#ffffff", "Defensive"),
    team!("Sampdoria", "Genoa", "Italy", 2, "#2563eb", "#ffffff", "Possession"),
    team!("Sassuolo", "Sassuolo", "Italy", 2, "#16a34a", "#111827", "Attacking"),
    team!("Spezia", "La Spezia", "Italy", 2, "#ffffff", "#111827", "Counter"),
    team!("Südtirol", "Bolzano", "Italy", 2, "#dc2626", "#ffffff", "Balanced"),

    team!("Real Madrid", "Madrid", "Spain", 1, "#ffffff", "#d4af37", "Possession"),
    team!("Barcelona", "Barcelona", "Spain", 1, "#9f1239", "#1d4ed8", "Attacking"),
    team!("Atlético Madrid", "Madrid", "Spain", 1, "#dc2626", "#ffffff", "Counter"),
    team!("Athletic Club", "Bilbao", "Spain", 1, "#dc2626", "#ffffff", "HighPress"),
    team!("Real Sociedad", "San Sebastián", "Spain", 1, "#2563eb", "#ffffff", "Possession"),
    team!("Real Betis", "Seville", "Spain", 1, "#16a34a", "#ffffff", "Attacking"),
    team!("Sevilla", "Seville", "Spain", 1, "#ffffff", "#dc2626", "Counter"),
    team!("Valencia", "Valencia", "Spain", 1, "#ffffff", "#111827", "Possession"),
    team!("Villarreal", "Villarreal", "Spain", 1, "#facc15", "#1d4ed8", "Attacking"),
    team!("Getafe", "Getafe", "Spain", 1, "#2563eb", "#ffffff", "Defensive"),
    team!("Celta Vigo", "Vigo", "Spain", 1, "#60a5fa", "#ffffff", "Balanced"),
    team!("Osasuna", "Pamplona", "Spain", 1, "#dc2626", "#1e3a8a", "HighPress"),
    team!("Mallorca", "Palma", "Spain", 1, "#dc2626", "#111827", "Counter"),
    team!("Rayo Vallecano", "Madrid", "Spain", 1, "#ffffff", "#dc2626", "HighPress"),
    team!("Girona", "Girona", "Spain", 1, "#dc2626", "#ffffff", "Possession"),
    team!("Alavés", "Vitoria-Gasteiz", "Spain", 1, "#2563eb", "#ffffff", "Defensive"),
    team!("Las Palmas", "Las Palmas", "Spain", 1, "#facc15", "#1d4ed8", "Possession"),
    team!("Leganés", "Leganés", "Spain", 1, "#2563eb", "#ffffff", "Counter"),
    team!("Espanyol", "Barcelona", "Spain", 1, "#2563eb", "#ffffff", "Balanced"),
    team!("Valladolid", "Valladolid", "Spain", 1, "#7c3aed", "#ffffff", "Possession"),
    team!("Albacete", "Albacete", "Spain", 2, "#ffffff", "#111827", "Balanced"),
    team!("Almería", "Almería", "Spain", 2, "#dc2626", "#ffffff", "Attacking"),
    team!("Burgos", "Burgos", "Spain", 2, "#ffffff", "#111827", "Defensive"),
    team!("Cádiz", "Cádiz", "Spain", 2, "#facc15", "#1d4ed8", "Counter"),
    team!("Cartagena", "Cartagena", "Spain", 2, "#111827", "#ffffff", "Balanced"),
    team!("Castellón", "Castellón", "Spain", 2, "#ffffff", "#111827", "Possession"),
    team!("Córdoba", "Córdoba", "Spain", 2, "#16a34a", "#ffffff", "HighPress"),
    team!("Deportivo La Coruña", "A Coruña", "Spain", 2, "#2563eb", "#ffffff", "Possession"),
    team!("Eibar", "Eibar", "Spain", 2, "#1d4ed8", "#7f1d1d", "Counter"),
    team!("Elche", "Elche", "Spain", 2, "#ffffff", "#16a34a", "Balanced"),
    team!("Eldense", "Elda", "Spain", 2, "#1d4ed8", "#dc2626", "Defensive"),
    team!("Granada", "Granada", "Spain", 2, "#dc2626", "#ffffff", "Possession"),
    team!("Huesca", "Huesca", "Spain", 2, "#1d4ed8", "#dc2626", "Counter"),
    team!("Levante", "Valencia", "Spain", 2, "#1d4ed8", "#7f1d1d", "Attacking"),
    team!("Málaga", "Málaga", "Spain", 2, "#60a5fa", "#ffffff", "Possession"),
    team!("Mirandés", "Miranda de Ebro", "Spain", 2, "#dc2626", "#111827", "HighPress"),
    team!("Racing Ferrol", "Ferrol", "Spain", 2, "#16a34a", "#ffffff", "Defensive"),
    team!("Racing Santander", "Santander", "Spain", 2, "#16a34a", "#ffffff", "Counter"),
    team!("Real Oviedo", "Oviedo", "Spain", 2, "#2563eb", "#ffffff", "Possession"),
    team!("Real Zaragoza", "Zaragoza", "Spain", 2, "#ffffff", "#2563eb", "Attacking"),

    team!("Benfica", "Lisbon", "Portugal", 1, "#dc2626", "#ffffff", "Attacking"),
    team!("Porto", "Porto", "Portugal", 1, "#1d4ed8", "#ffffff", "Possession"),
    team!("Sporting CP", "Lisbon", "Portugal", 1, "#16a34a", "#ffffff", "HighPress"),
    team!("Braga", "Braga", "Portugal", 1, "#dc2626", "#ffffff", "Attacking"),
    team!("Vitória Guimarães", "Guimarães", "Portugal", 1, "#ffffff", "#111827", "Counter"),
    team!("Boavista", "Porto", "Portugal", 1, "#111827", "#ffffff", "Defensive"),
    team!("Casa Pia", "Lisbon", "Portugal", 1, "#111827", "#ffffff", "Balanced"),
    team!("Estoril", "Estoril", "Portugal", 1, "#facc15", "#2563eb", "Possession"),
    team!("Famalicão", "Vila Nova de Famalicão", "Portugal", 1, "#ffffff", "#1d4ed8", "Balanced"),
    team!("Farense", "Faro", "Portugal", 1, "#111827", "#ffffff", "Counter"),
    team!("Gil Vicente", "Barcelos", "Portugal", 1, "#dc2626", "#1d4ed8", "Balanced"),
    team!("Moreirense", "Moreira de Cónegos", "Portugal", 1, "#16a34a", "#ffffff", "Counter"),
    team!("Nacional", "Funchal", "Portugal", 1, "#111827", "#ffffff", "Defensive"),
    team!("Rio Ave", "Vila do Conde", "Portugal", 1, "#16a34a", "#ffffff", "Possession"),
    team!("Santa Clara", "Ponta Delgada", "Portugal", 1, "#dc2626", "#ffffff", "HighPress"),
    team!("Arouca", "Arouca", "Portugal", 1, "#facc15", "#1d4ed8", "Counter"),
    team!("AVS", "Vila das Aves", "Portugal", 1, "#dc2626", "#ffffff", "Balanced"),
    team!("Estrela da Amadora", "Amadora", "Portugal", 1, "#dc2626", "#16a34a", "HighPress"),

    team!("Ajax", "Amsterdam", "Netherlands", 1, "#dc2626", "#ffffff", "Possession"),
    team!("PSV Eindhoven", "Eindhoven", "Netherlands", 1, "#dc2626", "#ffffff", "Attacking"),
    team!("Feyenoord", "Rotterdam", "Netherlands", 1, "#dc2626", "#ffffff", "HighPress"),
    team!("AZ Alkmaar", "Alkmaar", "Netherlands", 1, "#dc2626", "#ffffff", "Possession"),
    team!("Twente", "Enschede", "Netherlands", 1, "#dc2626", "#ffffff", "HighPress"),
    team!("Utrecht", "Utrecht", "Netherlands", 1, "#dc2626", "#ffffff", "Balanced"),
    team!("Heerenveen", "Heerenveen", "Netherlands", 1, "#2563eb", "#ffffff", "Counter"),
    team!("Groningen", "Groningen", "Netherlands", 1, "#16a34a", "#ffffff", "Balanced"),
    team!("Sparta Rotterdam", "Rotterdam", "Netherlands", 1, "#dc2626", "#ffffff", "Defensive"),
    team!("PEC Zwolle", "Zwolle", "Netherlands", 1, "#2563eb", "#ffffff", "Possession"),
    team!("Heracles Almelo", "Almelo", "Netherlands", 1, "#111827", "#ffffff", "Counter"),
    team!("NEC Nijmegen", "Nijmegen", "Netherlands", 1, "#dc2626", "#16a34a", "HighPress"),
    team!("NAC Breda", "Breda", "Netherlands", 1, "#facc15", "#111827", "Balanced"),
    team!("RKC Waalwijk", "Waalwijk", "Netherlands", 1, "#facc15", "#1d4ed8", "Counter"),
    team!("Go Ahead Eagles", "Deventer", "Netherlands", 1, "#dc2626", "#facc15", "HighPress"),
    team!("Willem II", "Tilburg", "Netherlands", 1, "#dc2626", "#1d4ed8", "Balanced"),
    team!("Fortuna Sittard", "Sittard", "Netherlands", 1, "#16a34a", "#facc15", "Defensive"),
    team!("Almere City", "Almere", "Netherlands", 1, "#dc2626", "#111827", "Counter"),

    team!("Club Brugge", "Bruges", "Belgium", 1, "#1d4ed8", "#111827", "Attacking"),
    team!("Anderlecht", "Brussels", "Belgium", 1, "#7c3aed", "#ffffff", "Possession"),
    team!("Genk", "Genk", "Belgium", 1, "#2563eb", "#ffffff", "HighPress"),
    team!("Gent", "Ghent", "Belgium", 1, "#2563eb", "#ffffff", "Balanced"),
    team!("Royal Antwerp", "Antwerp", "Belgium", 1, "#dc2626", "#ffffff", "Counter"),
    team!("Standard Liège", "Liège", "Belgium", 1, "#dc2626", "#ffffff", "HighPress"),
    team!("Union Saint-Gilloise", "Brussels", "Belgium", 1, "#facc15", "#1d4ed8", "Attacking"),
    team!("Mechelen", "Mechelen", "Belgium", 1, "#facc15", "#dc2626", "Balanced"),
    team!("Cercle Brugge", "Bruges", "Belgium", 1, "#16a34a", "#111827", "Counter"),
    team!("Charleroi", "Charleroi", "Belgium", 1, "#111827", "#ffffff", "Defensive"),
    team!("OH Leuven", "Leuven", "Belgium", 1, "#ffffff", "#111827", "Possession"),
    team!("Sint-Truiden", "Sint-Truiden", "Belgium", 1, "#facc15", "#1d4ed8", "Balanced"),
    team!("Westerlo", "Westerlo", "Belgium", 1, "#facc15", "#1d4ed8", "Counter"),
    team!("Kortrijk", "Kortrijk", "Belgium", 1, "#dc2626", "#ffffff", "HighPress"),
    team!("Beerschot", "Antwerp", "Belgium", 1, "#7c3aed", "#ffffff", "Defensive"),
    team!("Dender", "Denderleeuw", "Belgium", 1, "#1d4ed8", "#111827", "Counter"),
];
